@startuml layers

left to right direction

agent client as cli

node controller [
  controller layer
]

node service [
  service layer
]

node data [
  data access layer
]

cli ..> controller
controller ..> service
service ..> data
data ..> service
service ..> controller
controller ..> cli
@enduml
